#!/bin/bash

clear
while true; do
echo Listen to keys...
read -rsn1 input
if [ "$input" = "a" ]; then
    a
elif [ "$input" = "f" ]; then
    f
elif [ "$input" = "g" ]; then
    g
elif [ "$input" = "s" ]; then
    s
elif [ "$input" = "q" ]; then
    exit 0
fi
done
